import type { SearchEntry } from "./search";

/**
 * Handgepflegter Suchindex – bewusst kein Ableiten aus registry.ts.
 *
 * Ein Client-Import von registry.ts würde jedes manifest.ts mitziehen, und
 * jedes manifest.ts importiert seine `'use client'`-Component. Damit läge
 * der komplette Tool-Code jeder Seite im Suchfeld-Chunk – gemessen an einem
 * bestehenden Export sind das ~136 KB roh für nichts, was die Suche
 * tatsächlich braucht (siehe SiteFooter.tsx, das genau diesen Fehler heute
 * schon macht). Dieses Modul importiert nichts als den Typ und bleibt so in
 * einem einzigen kleinen, seitenweit gecachten Chunk.
 *
 * Zweiter Grund: Taglines sind 100–180 Zeichen lang und brechen im Dropdown
 * um, also braucht es ohnehin einen eigenen kurzen `hint`. Und Tags sind
 * redaktionelle Synonyme ("Kartons", "kWh", "KGV") – aus keinem vorhandenen
 * Feld ableitbar.
 *
 * Der Preis: diese Liste kann von registry.ts abweichen. src/lib/searchIndex.test.ts
 * hält beide synchron – wer ein Tool hinzufügt, bekommt dort einen roten Test
 * mit der Aufforderung, hier einen Eintrag zu ergänzen.
 */
export const searchIndex: SearchEntry[] = [
  {
    href: "/tools/brueckentage/",
    name: "Brückentage-Optimierer",
    hint: "Urlaubstage clever um Feiertage legen.",
    tags: [
      "Brückentage",
      "Feiertage",
      "Urlaub",
      "Urlaubstage",
      "freie Tage",
      "langes Wochenende",
      "Ferien",
      "Bundesland",
      "Urlaubsplanung",
    ],
  },
  {
    href: "/tools/trinkgeld/",
    name: "Trinkgeld-Splitter",
    hint: "Rechnung plus Trinkgeld fair aufteilen.",
    tags: [
      "Trinkgeld",
      "Tip",
      "Rechnung teilen",
      "splitten",
      "Restaurant",
      "Kellner",
      "Prozent",
      "Gruppe",
      "essen gehen",
    ],
  },
  {
    href: "/tools/lesezeit/",
    name: "Lesezeit-Rechner",
    hint: "Lese- und Sprechdauer aus einem Text schätzen.",
    tags: [
      "Lesezeit",
      "Lesedauer",
      "Wörter zählen",
      "Zeichen zählen",
      "Vortrag",
      "Rede",
      "Sprechdauer",
      "Podcast",
      "Manuskript",
    ],
  },
  {
    href: "/tools/elternzeit/",
    name: "Elternzeit-Planer",
    hint: "Elternzeit und Anmeldefristen rund um die Geburt.",
    tags: [
      "Elternzeit",
      "Elterngeld",
      "Mutterschutz",
      "Baby",
      "Geburt",
      "Partnermonate",
      "Lebensmonate",
      "Kind",
      "Antrag",
    ],
  },
  {
    href: "/tools/kuendigungsfrist/",
    name: "Kündigungsfrist-Rechner",
    hint: "Kündigungsfrist für Job oder Wohnung berechnen.",
    tags: [
      "Kündigung",
      "Kündigungsfrist",
      "Mietvertrag",
      "Arbeitsvertrag",
      "Wohnung kündigen",
      "Job kündigen",
      "Probezeit",
      "BGB",
      "Vermieter",
    ],
  },
  {
    href: "/tools/arbeitstage/",
    name: "Arbeitstage-Rechner",
    hint: "Werktage in einem Zeitraum zählen.",
    tags: [
      "Arbeitstage",
      "Werktage",
      "Feiertage",
      "Monat",
      "Jahr",
      "Zeitraum",
      "Gehalt",
      "Bundesland",
      "Kalender",
    ],
  },
  {
    href: "/tools/backform/",
    name: "Backform-Umrechner",
    hint: "Rezepte auf eine andere Backform umrechnen.",
    tags: [
      "Backform",
      "Springform",
      "Kastenform",
      "Backblech",
      "Kuchen",
      "Rezept umrechnen",
      "Zutaten",
      "Durchmesser",
      "backen",
    ],
  },
  {
    href: "/tools/umzug/",
    name: "Umzugs-Rechner",
    hint: "Kartons, Volumen und Transporter für den Umzug.",
    tags: [
      "Umzug",
      "Umzugskartons",
      "Kartons",
      "Transporter",
      "Volumen",
      "Kubikmeter",
      "m3",
      "Möbel",
      "packen",
      "Umzugswagen",
    ],
  },
  {
    href: "/tools/partymengen/",
    name: "Party- und Grillmengen",
    hint: "Essen und Trinken pro Person für die Feier.",
    tags: [
      "Party",
      "Grillen",
      "Grillfest",
      "Fleisch",
      "Getränke",
      "Bier",
      "Buffet",
      "Gäste",
      "Einkaufsliste",
      "Geburtstag",
    ],
  },
  {
    href: "/tools/stromkosten/",
    name: "Stromkosten-Rechner",
    hint: "Was ein Gerät im Jahr an Strom kostet.",
    tags: [
      "Strom",
      "Stromkosten",
      "Stromverbrauch",
      "kWh",
      "Watt",
      "Standby",
      "Kühlschrank",
      "Trockner",
      "Energie",
      "Verbrauch",
    ],
  },
  {
    href: "/tools/kindergeld/",
    name: "Kindergeld-Rechner",
    hint: "Kindergeld und Kinderfreibetrag vergleichen.",
    tags: [
      "Kindergeld",
      "Kinderfreibetrag",
      "Familienkasse",
      "Günstigerprüfung",
      "Kind",
      "Familie",
      "Freibetrag",
      "Steuer",
      "259 Euro",
    ],
  },
  {
    href: "/tools/kindergeld/guenstigerpruefung-kinderfreibetrag/",
    name: "Günstigerprüfung",
    hint: "Freibetrag oder Kindergeld – was ist besser?",
    parentName: "Kindergeld-Rechner",
    tags: [
      "Günstigerprüfung",
      "Freibetrag oder Kindergeld",
      "Anrechnung",
      "Soli",
    ],
  },
  {
    href: "/tools/kindergeld/kindergeld-studium/",
    name: "Kindergeld im Studium",
    hint: "Anspruch bis 25 bei Ausbildung.",
    parentName: "Kindergeld-Rechner",
    tags: ["Studium", "Ausbildung", "bis 25", "Nebenjob", "Master", "Student"],
  },
  {
    href: "/tools/urlaubsbudget/",
    name: "Urlaubsbudget-Planer",
    hint: "Reisekosten planen und dafür sparen.",
    tags: [
      "Urlaub",
      "Urlaubsbudget",
      "Reisekosten",
      "Reisebudget",
      "Urlaubskasse",
      "Tagesbudget",
      "Familienurlaub",
      "sparen",
      "Reise planen",
    ],
  },
  {
    href: "/tools/urlaubsbudget/urlaubskasse-sparen/",
    name: "Für den Urlaub sparen",
    hint: "Monatliche Sparrate bis zur Abreise.",
    parentName: "Urlaubsbudget-Planer",
    tags: [
      "Urlaubskasse",
      "sparen",
      "Sparrate",
      "Dauerauftrag",
      "Reise ansparen",
    ],
  },
  {
    href: "/tools/energiekosten/",
    name: "Energiekosten-Rechner",
    hint: "Strom- und Gasrechnung des Haushalts prüfen.",
    tags: [
      "Energiekosten",
      "Stromrechnung",
      "Gaskosten",
      "Abschlag",
      "Nachzahlung",
      "Grundpreis",
      "Arbeitspreis",
      "Jahresabrechnung",
      "Tarifwechsel",
      "kWh Preis",
    ],
  },
  {
    href: "/tools/energiekosten/abschlag-berechnen/",
    name: "Abschlag berechnen",
    hint: "Wie hoch die monatliche Zahlung sein sollte.",
    parentName: "Energiekosten-Rechner",
    tags: [
      "Abschlag",
      "Vorauszahlung",
      "monatlich",
      "Abschlag senken",
      "Abschlag anpassen",
    ],
  },
  {
    href: "/tools/energiekosten/nachzahlung-stromrechnung/",
    name: "Nachzahlung Stromrechnung",
    hint: "Was bei der Jahresabrechnung fehlt.",
    parentName: "Energiekosten-Rechner",
    tags: [
      "Nachzahlung",
      "Stromrechnung",
      "Guthaben",
      "Jahresabrechnung",
      "Ratenzahlung",
    ],
  },
  {
    href: "/tools/immobilienrechner/",
    name: "Immobilien-Rechner",
    hint: "Kaufnebenkosten, Mietrendite und Finanzierung.",
    tags: [
      "Immobilie",
      "Hauskauf",
      "Wohnung kaufen",
      "Kaufnebenkosten",
      "Grunderwerbsteuer",
      "Notar",
      "Makler",
      "Mietrendite",
      "Finanzierung",
      "Tilgung",
      "Kredit",
      "kaufen oder mieten",
    ],
  },
  {
    href: "/tools/aktienkennzahlen/",
    name: "Aktien-Kennzahlen-Rechner",
    hint: "Dreißig Kennzahlen aus einem Geschäftsbericht.",
    tags: [
      "Aktien",
      "Börse",
      "Kennzahlen",
      "Bewertung",
      "Dividende",
      "Bilanz",
      "Cashflow",
      "Fundamentalanalyse",
      "fairer Wert",
      "Geschäftsbericht",
    ],
  },
  {
    href: "/tools/aktienkennzahlen/kgv-berechnen/",
    name: "KGV berechnen",
    hint: "Kurs-Gewinn-Verhältnis einer Aktie berechnen.",
    parentName: "Aktien-Kennzahlen-Rechner",
    tags: [
      "KGV",
      "Kurs-Gewinn-Verhältnis",
      "P/E",
      "PE Ratio",
      "Gewinn je Aktie",
      "Bewertung",
    ],
  },
  {
    href: "/tools/aktienkennzahlen/kurs-buchwert-verhaeltnis/",
    name: "Kurs-Buchwert-Verhältnis berechnen",
    hint: "KBV einer Aktie berechnen.",
    parentName: "Aktien-Kennzahlen-Rechner",
    tags: ["KBV", "Kurs-Buchwert-Verhältnis", "P/B", "Buchwert", "Substanz"],
  },
  {
    href: "/tools/aktienkennzahlen/kurs-umsatz-verhaeltnis/",
    name: "Kurs-Umsatz-Verhältnis berechnen",
    hint: "KUV einer Aktie berechnen.",
    parentName: "Aktien-Kennzahlen-Rechner",
    tags: ["KUV", "Kurs-Umsatz-Verhältnis", "P/S", "Umsatzmultiplikator"],
  },
  {
    href: "/tools/aktienkennzahlen/peg-ratio/",
    name: "PEG-Ratio berechnen",
    hint: "KGV im Verhältnis zum Gewinnwachstum.",
    parentName: "Aktien-Kennzahlen-Rechner",
    tags: ["PEG", "PEG-Ratio", "Wachstum", "KGV Wachstum"],
  },
  {
    href: "/tools/aktienkennzahlen/dividendenrendite-berechnen/",
    name: "Dividendenrendite berechnen",
    hint: "Dividendenrendite und Ausschüttungsquote.",
    parentName: "Aktien-Kennzahlen-Rechner",
    tags: ["Dividendenrendite", "Dividende", "Ausschüttung", "Rendite"],
  },
  {
    href: "/tools/aktienkennzahlen/ausschuettungsquote-berechnen/",
    name: "Ausschüttungsquote berechnen",
    hint: "Ist die Dividende durch den Gewinn gedeckt?",
    parentName: "Aktien-Kennzahlen-Rechner",
    tags: ["Ausschüttungsquote", "Payout Ratio", "Dividende gedeckt"],
  },
  {
    href: "/tools/aktienkennzahlen/eigenkapitalrendite-berechnen/",
    name: "Eigenkapitalrendite berechnen",
    hint: "ROE einer Aktie berechnen.",
    parentName: "Aktien-Kennzahlen-Rechner",
    tags: ["Eigenkapitalrendite", "ROE", "Return on Equity", "Rentabilität"],
  },
  {
    href: "/tools/aktienkennzahlen/ev-ebitda-berechnen/",
    name: "EV/EBITDA berechnen",
    hint: "Unternehmenswert zum operativen Ergebnis.",
    parentName: "Aktien-Kennzahlen-Rechner",
    tags: [
      "EV/EBITDA",
      "Enterprise Value",
      "Unternehmenswert",
      "EBITDA",
      "Nettoschulden",
    ],
  },
  {
    href: "/tools/aktienkennzahlen/free-cashflow-rendite-berechnen/",
    name: "Free-Cashflow-Rendite berechnen",
    hint: "Cashflow-Rendite einer Aktie berechnen.",
    parentName: "Aktien-Kennzahlen-Rechner",
    tags: ["Free Cashflow", "FCF", "Cashflow-Rendite", "freier Cashflow"],
  },
  {
    href: "/tools/aktienkennzahlen/eigenkapitalquote-berechnen/",
    name: "Eigenkapitalquote berechnen",
    hint: "Bilanzstärke und Verschuldungsgrad prüfen.",
    parentName: "Aktien-Kennzahlen-Rechner",
    tags: ["Eigenkapitalquote", "Bilanzstärke", "Verschuldung", "Bilanz"],
  },
  {
    href: "/tools/sparplan/",
    name: "Sparplan-Rechner",
    hint: "Sparrate, Zinseszins, Steuern und Entnahme.",
    tags: [
      "Sparplan",
      "Zinseszins",
      "ETF",
      "sparen",
      "Rendite",
      "Vermögensaufbau",
      "Altersvorsorge",
      "Depot",
      "Abgeltungssteuer",
      "Vorabpauschale",
    ],
  },
  {
    href: "/tools/sparplan/zinseszinsrechner/",
    name: "Zinseszins berechnen",
    hint: "Kapital über die Jahre mit Zinseszins berechnen.",
    parentName: "Sparplan-Rechner",
    tags: ["Zinseszins", "Zinsen", "Kapital", "Verdopplung", "72er-Regel"],
  },
  {
    href: "/tools/sparplan/sparrate-berechnen/",
    name: "Sparrate berechnen",
    hint: "Nötige Monatsrate für ein Sparziel.",
    parentName: "Sparplan-Rechner",
    tags: ["Sparrate", "Sparziel", "wie viel sparen", "Monatsrate"],
  },
  {
    href: "/tools/sparplan/vorabpauschale-berechnen/",
    name: "Vorabpauschale berechnen",
    hint: "ETF-Steuer im Januar mit Basiszins 2026.",
    parentName: "Sparplan-Rechner",
    tags: [
      "Vorabpauschale",
      "Basiszins",
      "ETF-Steuer",
      "thesaurierend",
      "InvStG",
    ],
  },
  {
    href: "/tools/sparplan/abgeltungssteuer-berechnen/",
    name: "Abgeltungssteuer berechnen",
    hint: "25 Prozent plus Soli und Kirchensteuer.",
    parentName: "Sparplan-Rechner",
    tags: [
      "Abgeltungssteuer",
      "Abgeltungsteuer",
      "Kapitalertragsteuer",
      "Sparerpauschbetrag",
      "Kirchensteuer",
    ],
  },
  {
    href: "/tools/sparplan/entnahmeplan-rechner/",
    name: "Entnahmeplan berechnen",
    hint: "Monatliche Entnahme aus einem Vermögen.",
    parentName: "Sparplan-Rechner",
    tags: ["Entnahmeplan", "Entnahme", "4-Prozent-Regel", "Ruhestand", "Rente"],
  },
  {
    href: "/tools/kreditrechner/",
    name: "Kredit-Rechner",
    hint: "Rate, Zinsen, Tilgungsplan und Effektivzins.",
    tags: [
      "Kredit",
      "Darlehen",
      "Ratenkredit",
      "Zinsen",
      "Tilgung",
      "Monatsrate",
      "Finanzierung",
      "Bank",
      "Schulden",
    ],
  },
  {
    href: "/tools/kreditrechner/effektiver-jahreszins-berechnen/",
    name: "Effektiven Jahreszins berechnen",
    hint: "Echte Kreditkosten nach Preisangabenverordnung.",
    parentName: "Kredit-Rechner",
    tags: [
      "Effektivzins",
      "effektiver Jahreszins",
      "Sollzins",
      "PAngV",
      "Bearbeitungsgebühr",
    ],
  },
  {
    href: "/tools/kreditrechner/sondertilgung-rechner/",
    name: "Sondertilgung berechnen",
    hint: "Wie viel Zinsen und Laufzeit sie spart.",
    parentName: "Kredit-Rechner",
    tags: [
      "Sondertilgung",
      "vorzeitig tilgen",
      "schuldenfrei",
      "Zinsersparnis",
    ],
  },
  {
    href: "/tools/kreditrechner/restschuld-berechnen/",
    name: "Restschuld berechnen",
    hint: "Was am Ende der Zinsbindung offen bleibt.",
    parentName: "Kredit-Rechner",
    tags: [
      "Restschuld",
      "Zinsbindung",
      "Anschlussfinanzierung",
      "Forward-Darlehen",
    ],
  },
  {
    href: "/tools/kreditrechner/umschuldung-rechner/",
    name: "Umschuldung berechnen",
    hint: "Was ein günstigerer Kredit spart.",
    parentName: "Kredit-Rechner",
    tags: ["Umschuldung", "umschulden", "Dispo", "ablösen", "Kredit tauschen"],
  },
  {
    href: "/tools/bruttonetto/",
    name: "Brutto-Netto-Rechner",
    hint: "Was vom Gehalt übrig bleibt, Posten für Posten.",
    tags: [
      "Brutto",
      "Netto",
      "Gehalt",
      "Lohn",
      "Gehaltsrechner",
      "Lohnrechner",
      "Lohnsteuer",
      "Sozialabgaben",
      "Steuerklasse",
      "Verdienst",
    ],
  },
  {
    href: "/tools/bruttonetto/sozialabgaben-berechnen/",
    name: "Sozialabgaben berechnen",
    hint: "Alle vier Zweige mit Bemessungsgrenzen.",
    parentName: "Brutto-Netto-Rechner",
    tags: [
      "Sozialabgaben",
      "Sozialversicherung",
      "Rentenversicherung",
      "Krankenversicherung",
      "Pflegeversicherung",
      "Beitragsbemessungsgrenze",
    ],
  },
  {
    href: "/tools/bruttonetto/kirchensteuer-berechnen/",
    name: "Kirchensteuer berechnen",
    hint: "8 oder 9 Prozent der Lohnsteuer.",
    parentName: "Brutto-Netto-Rechner",
    tags: [
      "Kirchensteuer",
      "Kirchenaustritt",
      "Kirche",
      "8 Prozent",
      "9 Prozent",
    ],
  },
  {
    href: "/tools/bruttonetto/arbeitgeberkosten-berechnen/",
    name: "Arbeitgeberkosten berechnen",
    hint: "Was eine Stelle wirklich kostet.",
    parentName: "Brutto-Netto-Rechner",
    tags: [
      "Arbeitgeberkosten",
      "Lohnnebenkosten",
      "Arbeitgeberbrutto",
      "Personalkosten",
    ],
  },
  {
    href: "/tools/rentenluecke/",
    name: "Rentenlücken-Rechner",
    hint: "Kapitalbedarf und Sparrate für den Ruhestand.",
    tags: [
      "Rentenlücke",
      "Altersvorsorge",
      "gesetzliche Rente",
      "Kapitalbedarf",
      "Versorgungsniveau",
      "Ruhestand",
      "Rentenniveau",
      "Sparrate Rente",
      "private Vorsorge",
    ],
  },
  {
    href: "/tools/elterngeld/",
    name: "Elterngeld-Rechner",
    hint: "Ersatzrate, Boni und ElterngeldPlus im Vergleich.",
    tags: [
      "Elterngeld",
      "ElterngeldPlus",
      "Basiselterngeld",
      "Geschwisterbonus",
      "Mehrlingszuschlag",
      "Ersatzrate",
      "Elternzeit Geld",
      "Partnermonate",
    ],
  },
  {
    href: "/tools/rentenabschlag/",
    name: "Rentenabschlags-Rechner",
    hint: "Abschlag oder Zuschlag je nach Renteneintritt.",
    tags: [
      "Rentenabschlag",
      "Regelaltersgrenze",
      "früher in Rente",
      "Rente mit 63",
      "Rentenzuschlag",
      "Renteneintrittsalter",
      "Zugangsfaktor",
    ],
  },
  {
    href: "/tools/abfindung/",
    name: "Abfindungsrechner",
    hint: "Fünftelregelung: Steuer auf die Abfindung.",
    tags: [
      "Abfindung",
      "Fünftelregelung",
      "Abfindung versteuern",
      "Abfindung netto",
      "Kündigung Steuer",
      "Aufhebungsvertrag",
    ],
  },
  {
    href: "/tools/erbschaftsteuer/",
    name: "Erbschaft- und Schenkungsteuer-Rechner",
    hint: "Freibetrag, Steuerklasse und Härteausgleich.",
    tags: [
      "Erbschaftsteuer",
      "Schenkungsteuer",
      "Erbschaft",
      "Schenkung",
      "Freibetrag",
      "Steuerklasse",
      "Härteausgleich",
      "ErbStG",
      "Nachlass",
    ],
  },
  {
    href: "/tools/versicherungsvergleich/",
    name: "Versicherungs-Vergleichsrechner",
    hint: "Marktdurchschnitt für Kfz, Haftpflicht und BU.",
    tags: [
      "Versicherungsvergleich",
      "Kfz-Versicherung",
      "Privathaftpflicht",
      "Berufsunfähigkeitsversicherung",
      "BU",
      "Durchschnittsbeitrag",
      "Schadenfreiheitsklasse",
      "zu teuer versichert",
      "Prämie vergleichen",
    ],
  },
  {
    href: "/tools/autokosten/",
    name: "Auto-Unterhaltskosten-Rechner",
    hint: "Wertverlust, Sprit, Steuer und Versicherung.",
    tags: [
      "Autokosten",
      "Unterhaltskosten",
      "Wertverlust",
      "Kraftstoffkosten",
      "Kfz-Steuer",
      "Kfz-Versicherung",
      "Kosten pro Kilometer",
      "Auto Unterhalt",
      "Elektroauto Kosten",
    ],
  },
  {
    href: "/tools/bmi/",
    name: "BMI-Rechner",
    hint: "Body-Mass-Index mit WHO-Kategorie.",
    tags: [
      "BMI",
      "Body Mass Index",
      "BMI berechnen",
      "Normalgewicht",
      "Idealgewicht",
      "Übergewicht",
      "BMI Tabelle",
      "BMI Rechner",
    ],
  },
  {
    href: "/tools/kalorienbedarf/",
    name: "Kalorienbedarf-Rechner",
    hint: "Grundumsatz und Gesamtumsatz pro Tag.",
    tags: [
      "Kalorienbedarf",
      "Grundumsatz",
      "Gesamtumsatz",
      "Kalorien pro Tag",
      "Mifflin-St Jeor",
      "PAL",
      "Kalorienrechner",
      "Aktivitätsfaktor",
    ],
  },
  {
    href: "/wege/hauskauf/",
    name: "Check: Hauskauf",
    hint: "Immobilie und Einkommen zusammen: leistbar oder nicht?",
    tags: [
      "Hauskauf",
      "Haus kaufen",
      "kann ich mir ein Haus leisten",
      "wie viel Haus kann ich mir leisten",
      "Belastungsquote",
      "Baufinanzierung tragbar",
      "Immobilie leisten",
    ],
  },
  {
    href: "/wege/gehalt/",
    name: "Check: Gehaltserhöhung",
    hint: "Brutto-Plus, Netto-Plus und Grenzbelastung in einem Zug.",
    tags: [
      "Gehaltserhöhung",
      "Gehaltserhöhung netto",
      "Grenzbelastung",
      "was bringt gehaltserhöhung",
      "gehaltserhöhung berechnen",
      "gehaltserhöhung sparen",
    ],
  },
  {
    href: "/wege/ruhestand/",
    name: "Check: Ruhestand",
    hint: "Rente nach Abschlag, Kapitalbedarf und Sparrate zusammen.",
    tags: [
      "Früher in Rente",
      "Rente mit 63",
      "Renteneintritt vorziehen",
      "kann ich früher in rente gehen",
      "wann kann ich in rente gehen",
      "Rentenlücke",
      "Rentenabschlag",
    ],
  },
  {
    href: "/wege/autokauf/",
    name: "Check: Auto",
    hint: "Kreditrate, Unterhalt und Versicherung gegen das Netto.",
    tags: [
      "Autokauf",
      "Auto finanzieren",
      "was kostet ein auto wirklich",
      "kann ich mir das auto leisten",
      "Autokosten Rate",
      "Auto Gesamtkosten",
    ],
  },
  {
    href: "/wege/nachwuchs/",
    name: "Check: Nachwuchs",
    hint: "Termin, Einkommen, Elterngeld und Elternzeit zusammen.",
    tags: [
      "Elterngeld",
      "Elternzeit",
      "Kindergeld",
      "was bringt elterngeld",
      "elternzeit planen",
      "geburtstermin",
      "Nachwuchs",
    ],
  },
  {
    href: "/tools/prozentrechner/",
    name: "Prozentrechner",
    hint: "Anteil, Grundwert, Prozentsatz oder Veränderung berechnen.",
    tags: [
      "Prozentrechner",
      "Prozent berechnen",
      "Prozentsatz",
      "Grundwert",
      "Prozentwert",
      "Rabatt berechnen",
      "wie viel Prozent",
      "prozentuale Veränderung",
    ],
  },
  {
    href: "/tools/geburtstermin/",
    name: "Geburtstermin-Rechner",
    hint: "Errechneter Termin und Schwangerschaftswoche.",
    tags: [
      "Geburtstermin",
      "SSW",
      "Schwangerschaftswoche",
      "errechneter Termin",
      "Naegele-Regel",
      "Schwangerschaftskalender",
      "Entbindungstermin",
      "Trimester",
    ],
  },
];
