import type { SearchEntry } from "./search";

/**
 * Handgepflegter Suchindex – bewusst kein Ableiten aus registry.ts.
 *
 * Ein Client-Import von registry.ts würde jedes manifest.ts mitziehen, und
 * jedes manifest.ts importiert seine `'use client'`-Component. Damit läge
 * der komplette Tool-Code jeder Seite im Suchfeld-Chunk – gemessen an einem
 * bestehenden Export sind das ~136 KB roh für nichts, was die Suche
 * tatsächlich braucht (siehe SiteFooter.tsx, das genau diesen Fehler heute
 * schon macht). Dieses Modul importiert nichts als den Typ und bleibt so in
 * einem einzigen kleinen, seitenweit gecachten Chunk.
 *
 * Zweiter Grund: Taglines sind 100–180 Zeichen lang und brechen im Dropdown
 * um, also braucht es ohnehin einen eigenen kurzen `hint`. Und Tags sind
 * redaktionelle Synonyme ("Kartons", "kWh", "KGV") – aus keinem vorhandenen
 * Feld ableitbar.
 *
 * Der Preis: diese Liste kann von registry.ts abweichen. src/lib/searchIndex.test.ts
 * hält beide synchron – wer ein Tool hinzufügt, bekommt dort einen roten Test
 * mit der Aufforderung, hier einen Eintrag zu ergänzen.
 */
export const searchIndex: SearchEntry[] = [
  {
    href: "/tools/brueckentage/",
    name: "Brückentage-Optimierer",
    hint: "Urlaubstage clever um Feiertage legen.",
    tags: [
      "Brückentage",
      "Feiertage",
      "Urlaub",
      "Urlaubstage",
      "freie Tage",
      "langes Wochenende",
      "Ferien",
      "Bundesland",
      "Urlaubsplanung",
    ],
  },
  {
    href: "/tools/trinkgeld/",
    name: "Trinkgeld-Splitter",
    hint: "Rechnung plus Trinkgeld fair aufteilen.",
    tags: [
      "Trinkgeld",
      "Tip",
      "Rechnung teilen",
      "splitten",
      "Restaurant",
      "Kellner",
      "Prozent",
      "Gruppe",
      "essen gehen",
    ],
  },
  {
    href: "/tools/lesezeit/",
    name: "Lesezeit-Rechner",
    hint: "Lese- und Sprechdauer aus einem Text schätzen.",
    tags: [
      "Lesezeit",
      "Lesedauer",
      "Wörter zählen",
      "Zeichen zählen",
      "Vortrag",
      "Rede",
      "Sprechdauer",
      "Podcast",
      "Manuskript",
    ],
  },
  {
    href: "/tools/elternzeit/",
    name: "Elternzeit-Planer",
    hint: "Elternzeit und Anmeldefristen rund um die Geburt.",
    tags: [
      "Elternzeit",
      "Elterngeld",
      "Mutterschutz",
      "Baby",
      "Geburt",
      "Partnermonate",
      "Lebensmonate",
      "Kind",
      "Antrag",
    ],
  },
  {
    href: "/tools/kuendigungsfrist/",
    name: "Kündigungsfrist-Rechner",
    hint: "Kündigungsfrist für Job oder Wohnung berechnen.",
    tags: [
      "Kündigung",
      "Kündigungsfrist",
      "Mietvertrag",
      "Arbeitsvertrag",
      "Wohnung kündigen",
      "Job kündigen",
      "Probezeit",
      "BGB",
      "Vermieter",
    ],
  },
  {
    href: "/tools/arbeitstage/",
    name: "Arbeitstage-Rechner",
    hint: "Werktage in einem Zeitraum zählen.",
    tags: [
      "Arbeitstage",
      "Werktage",
      "Feiertage",
      "Monat",
      "Jahr",
      "Zeitraum",
      "Gehalt",
      "Bundesland",
      "Kalender",
    ],
  },
  {
    href: "/tools/backform/",
    name: "Backform-Umrechner",
    hint: "Rezepte auf eine andere Backform umrechnen.",
    tags: [
      "Backform",
      "Springform",
      "Kastenform",
      "Backblech",
      "Kuchen",
      "Rezept umrechnen",
      "Zutaten",
      "Durchmesser",
      "backen",
    ],
  },
  {
    href: "/tools/backform/26-auf-20/",
    name: "Backform 26 auf 20 cm",
    hint: "Rezept von Ø 26 cm auf Ø 20 cm herunterrechnen.",
    parentName: "Backform-Umrechner",
    tags: ["26 auf 20", "26 cm", "20 cm", "verkleinern", "Springform"],
  },
  {
    href: "/tools/backform/26-auf-18/",
    name: "Backform 26 auf 18 cm",
    hint: "Rezept von Ø 26 cm auf Ø 18 cm herunterrechnen.",
    parentName: "Backform-Umrechner",
    tags: ["26 auf 18", "18 cm", "kleine Form", "verkleinern"],
  },
  {
    href: "/tools/backform/26-auf-24/",
    name: "Backform 26 auf 24 cm",
    hint: "Rezept von Ø 26 cm auf Ø 24 cm herunterrechnen.",
    parentName: "Backform-Umrechner",
    tags: ["26 auf 24", "24 cm", "verkleinern"],
  },
  {
    href: "/tools/backform/26-auf-28/",
    name: "Backform 26 auf 28 cm",
    hint: "Rezept von Ø 26 cm auf Ø 28 cm hochrechnen.",
    parentName: "Backform-Umrechner",
    tags: ["26 auf 28", "28 cm", "vergrößern", "größere Form"],
  },
  {
    href: "/tools/backform/24-auf-20/",
    name: "Backform 24 auf 20 cm",
    hint: "Rezept von Ø 24 cm auf Ø 20 cm herunterrechnen.",
    parentName: "Backform-Umrechner",
    tags: ["24 auf 20", "24 cm", "verkleinern"],
  },
  {
    href: "/tools/backform/24-auf-26/",
    name: "Backform 24 auf 26 cm",
    hint: "Rezept von Ø 24 cm auf Ø 26 cm hochrechnen.",
    parentName: "Backform-Umrechner",
    tags: ["24 auf 26", "vergrößern"],
  },
  {
    href: "/tools/backform/22-auf-26/",
    name: "Backform 22 auf 26 cm",
    hint: "Rezept von Ø 22 cm auf Ø 26 cm hochrechnen.",
    parentName: "Backform-Umrechner",
    tags: ["22 auf 26", "22 cm", "vergrößern"],
  },
  {
    href: "/tools/backform/20-auf-26/",
    name: "Backform 20 auf 26 cm",
    hint: "Rezept von Ø 20 cm auf Ø 26 cm hochrechnen.",
    parentName: "Backform-Umrechner",
    tags: ["20 auf 26", "20 cm", "vergrößern"],
  },
  {
    href: "/tools/backform/18-auf-26/",
    name: "Backform 18 auf 26 cm",
    hint: "Rezept von Ø 18 cm auf Ø 26 cm hochrechnen.",
    parentName: "Backform-Umrechner",
    tags: ["18 auf 26", "vergrößern", "doppelte Menge"],
  },
  {
    href: "/tools/backform/28-auf-26/",
    name: "Backform 28 auf 26 cm",
    hint: "Rezept von Ø 28 cm auf Ø 26 cm herunterrechnen.",
    parentName: "Backform-Umrechner",
    tags: ["28 auf 26", "28 cm", "verkleinern"],
  },
  {
    href: "/tools/umzug/",
    name: "Umzugs-Rechner",
    hint: "Kartons, Volumen und Transporter für den Umzug.",
    tags: [
      "Umzug",
      "Umzugskartons",
      "Kartons",
      "Transporter",
      "Volumen",
      "Kubikmeter",
      "m3",
      "Möbel",
      "packen",
      "Umzugswagen",
    ],
  },
  {
    href: "/tools/umzug/30-qm/",
    name: "Umzugskartons für 30 m²",
    hint: "1-Zimmer-Wohnung: Kartons, Volumen, Transporter.",
    parentName: "Umzugs-Rechner",
    tags: ["30 qm", "1-Zimmer-Wohnung", "Single", "kleine Wohnung"],
  },
  {
    href: "/tools/umzug/50-qm/",
    name: "Umzugskartons für 50 m²",
    hint: "2-Zimmer-Wohnung: Kartons, Volumen, Transporter.",
    parentName: "Umzugs-Rechner",
    tags: ["50 qm", "2-Zimmer-Wohnung", "Paar"],
  },
  {
    href: "/tools/umzug/70-qm/",
    name: "Umzugskartons für 70 m²",
    hint: "3-Zimmer-Wohnung: Kartons, Volumen, Transporter.",
    parentName: "Umzugs-Rechner",
    tags: ["70 qm", "3-Zimmer-Wohnung", "Familie"],
  },
  {
    href: "/tools/umzug/90-qm/",
    name: "Umzugskartons für 90 m²",
    hint: "4-Zimmer-Wohnung: Kartons, Volumen, Transporter.",
    parentName: "Umzugs-Rechner",
    tags: ["90 qm", "4-Zimmer-Wohnung", "große Wohnung"],
  },
  {
    href: "/tools/umzug/120-qm/",
    name: "Umzugskartons für 120 m²",
    hint: "Haus mit 120 m²: Kartons, Volumen, Transporter.",
    parentName: "Umzugs-Rechner",
    tags: ["120 qm", "Haus", "Einfamilienhaus", "Hausumzug"],
  },
  {
    href: "/tools/partymengen/",
    name: "Party- und Grillmengen",
    hint: "Essen und Trinken pro Person für die Feier.",
    tags: [
      "Party",
      "Grillen",
      "Grillfest",
      "Fleisch",
      "Getränke",
      "Bier",
      "Buffet",
      "Gäste",
      "Einkaufsliste",
      "Geburtstag",
    ],
  },
  {
    href: "/tools/partymengen/grillen-fuer-10-personen/",
    name: "Grillen für 10 Personen",
    hint: "Fleisch, Beilagen und Getränke für 10 Gäste.",
    parentName: "Party- und Grillmengen",
    tags: ["10 Personen", "10 Gäste", "kleine Runde", "Grillfest"],
  },
  {
    href: "/tools/partymengen/grillen-fuer-15-personen/",
    name: "Grillen für 15 Personen",
    hint: "Fleisch, Beilagen und Getränke für 15 Gäste.",
    parentName: "Party- und Grillmengen",
    tags: ["15 Personen", "15 Gäste", "Grillfest"],
  },
  {
    href: "/tools/partymengen/grillen-fuer-20-personen/",
    name: "Grillen für 20 Personen",
    hint: "Fleisch, Beilagen und Getränke für 20 Gäste.",
    parentName: "Party- und Grillmengen",
    tags: ["20 Personen", "20 Gäste", "Gartenparty"],
  },
  {
    href: "/tools/partymengen/grillen-fuer-30-personen/",
    name: "Grillen für 30 Personen",
    hint: "Fleisch, Beilagen und Getränke für 30 Gäste.",
    parentName: "Party- und Grillmengen",
    tags: ["30 Personen", "30 Gäste", "große Feier"],
  },
  {
    href: "/tools/partymengen/grillen-fuer-50-personen/",
    name: "Grillen für 50 Personen",
    hint: "Fleisch, Beilagen und Getränke für 50 Gäste.",
    parentName: "Party- und Grillmengen",
    tags: ["50 Personen", "50 Gäste", "Hochzeit", "Vereinsfest"],
  },
  {
    href: "/tools/stromkosten/",
    name: "Stromkosten-Rechner",
    hint: "Was ein Gerät im Jahr an Strom kostet.",
    tags: [
      "Strom",
      "Stromkosten",
      "Stromverbrauch",
      "kWh",
      "Watt",
      "Standby",
      "Kühlschrank",
      "Trockner",
      "Energie",
      "Verbrauch",
    ],
  },
  {
    href: "/tools/stromkosten/trockner-stromkosten/",
    name: "Stromkosten Wäschetrockner",
    hint: "Was ein Trockner je Ladung und im Jahr kostet.",
    parentName: "Stromkosten-Rechner",
    tags: ["Trockner", "Wäschetrockner", "Wärmepumpentrockner", "Ladung"],
  },
  {
    href: "/tools/stromkosten/kuehlschrank-stromkosten/",
    name: "Stromkosten Kühlschrank",
    hint: "Dauerläufer im Haushalt – Kosten pro Jahr.",
    parentName: "Stromkosten-Rechner",
    tags: [
      "Kühlschrank",
      "Gefrierschrank",
      "Kühl-Gefrier-Kombi",
      "Dauerbetrieb",
    ],
  },
  {
    href: "/tools/stromkosten/heizluefter-stromkosten/",
    name: "Stromkosten Heizlüfter",
    hint: "2000 Watt – was eine Stunde Heizen kostet.",
    parentName: "Stromkosten-Rechner",
    tags: ["Heizlüfter", "Radiator", "elektrisch heizen", "2000 Watt"],
  },
  {
    href: "/tools/stromkosten/gaming-stromkosten/",
    name: "Stromkosten Gaming-PC",
    hint: "Was Spielen im Monat an Strom kostet.",
    parentName: "Stromkosten-Rechner",
    tags: ["Gaming", "Gaming-PC", "Konsole", "Grafikkarte", "PC"],
  },
  {
    href: "/tools/stromkosten/klimageraet-stromkosten/",
    name: "Stromkosten Klimagerät",
    hint: "Mobiles Klimagerät – Kosten je Sommertag.",
    parentName: "Stromkosten-Rechner",
    tags: ["Klimagerät", "Klimaanlage", "mobil", "Sommer", "kühlen"],
  },
  {
    href: "/tools/stromkosten/waschmaschine-stromkosten/",
    name: "Stromkosten Waschmaschine",
    hint: "Kosten je Waschgang und Waschprogramm.",
    parentName: "Stromkosten-Rechner",
    tags: ["Waschmaschine", "Waschgang", "60 Grad", "Eco-Programm"],
  },
  {
    href: "/tools/kindergeld/",
    name: "Kindergeld-Rechner",
    hint: "Kindergeld und Kinderfreibetrag vergleichen.",
    tags: [
      "Kindergeld",
      "Kinderfreibetrag",
      "Familienkasse",
      "Günstigerprüfung",
      "Kind",
      "Familie",
      "Freibetrag",
      "Steuer",
      "259 Euro",
    ],
  },
  {
    href: "/tools/kindergeld/kindergeld-2026/",
    name: "Kindergeld 2026",
    hint: "259 Euro je Kind – Höhe und Dauer.",
    parentName: "Kindergeld-Rechner",
    tags: ["Kindergeld 2026", "259 Euro", "Erhöhung", "Familienkasse"],
  },
  {
    href: "/tools/kindergeld/kinderfreibetrag-berechnen/",
    name: "Kinderfreibetrag berechnen",
    hint: "9.756 Euro und was sie an Steuer sparen.",
    parentName: "Kindergeld-Rechner",
    tags: [
      "Kinderfreibetrag",
      "Freibetrag",
      "9756",
      "Betreuungsfreibetrag",
      "BEA",
    ],
  },
  {
    href: "/tools/kindergeld/guenstigerpruefung-kinderfreibetrag/",
    name: "Günstigerprüfung",
    hint: "Freibetrag oder Kindergeld – was ist besser?",
    parentName: "Kindergeld-Rechner",
    tags: [
      "Günstigerprüfung",
      "Freibetrag oder Kindergeld",
      "Anrechnung",
      "Soli",
    ],
  },
  {
    href: "/tools/kindergeld/kindergeld-3-kinder/",
    name: "Kindergeld für 3 Kinder",
    hint: "777 Euro im Monat für drei Kinder.",
    parentName: "Kindergeld-Rechner",
    tags: [
      "3 Kinder",
      "drei Kinder",
      "Großfamilie",
      "777 Euro",
      "Mehrkindfamilie",
    ],
  },
  {
    href: "/tools/kindergeld/kindergeld-studium/",
    name: "Kindergeld im Studium",
    hint: "Anspruch bis 25 bei Ausbildung.",
    parentName: "Kindergeld-Rechner",
    tags: ["Studium", "Ausbildung", "bis 25", "Nebenjob", "Master", "Student"],
  },
  {
    href: "/tools/urlaubsbudget/",
    name: "Urlaubsbudget-Planer",
    hint: "Reisekosten planen und dafür sparen.",
    tags: [
      "Urlaub",
      "Urlaubsbudget",
      "Reisekosten",
      "Reisebudget",
      "Urlaubskasse",
      "Tagesbudget",
      "Familienurlaub",
      "sparen",
      "Reise planen",
    ],
  },
  {
    href: "/tools/urlaubsbudget/urlaubskasse-sparen/",
    name: "Für den Urlaub sparen",
    hint: "Monatliche Sparrate bis zur Abreise.",
    parentName: "Urlaubsbudget-Planer",
    tags: [
      "Urlaubskasse",
      "sparen",
      "Sparrate",
      "Dauerauftrag",
      "Reise ansparen",
    ],
  },
  {
    href: "/tools/urlaubsbudget/budget-2-wochen-urlaub/",
    name: "Budget für 2 Wochen Urlaub",
    hint: "Was eine zweiwöchige Reise kostet.",
    parentName: "Urlaubsbudget-Planer",
    tags: ["2 Wochen", "zwei Wochen Urlaub", "Reisebudget", "14 Nächte"],
  },
  {
    href: "/tools/urlaubsbudget/familienurlaub-kosten/",
    name: "Familienurlaub: die Kosten",
    hint: "Urlaub mit Kindern durchrechnen.",
    parentName: "Urlaubsbudget-Planer",
    tags: ["Familienurlaub", "Kinder", "Familie", "Ferien", "Schulferien"],
  },
  {
    href: "/tools/urlaubsbudget/tagesbudget-urlaub/",
    name: "Tagesbudget im Urlaub",
    hint: "Wie viel Geld pro Tag vor Ort.",
    parentName: "Urlaubsbudget-Planer",
    tags: ["Tagesbudget", "Geld pro Tag", "Taschengeld", "vor Ort", "Bargeld"],
  },
  {
    href: "/tools/energiekosten/",
    name: "Energiekosten-Rechner",
    hint: "Strom- und Gasrechnung des Haushalts prüfen.",
    tags: [
      "Energiekosten",
      "Stromrechnung",
      "Gaskosten",
      "Abschlag",
      "Nachzahlung",
      "Grundpreis",
      "Arbeitspreis",
      "Jahresabrechnung",
      "Tarifwechsel",
      "kWh Preis",
    ],
  },
  {
    href: "/tools/energiekosten/gaskosten-berechnen/",
    name: "Gaskosten berechnen",
    hint: "Gasrechnung aus Verbrauch und Preisen.",
    parentName: "Energiekosten-Rechner",
    tags: [
      "Gas",
      "Gaskosten",
      "Heizkosten",
      "Kubikmeter",
      "Brennwert",
      "Erdgas",
    ],
  },
  {
    href: "/tools/energiekosten/stromkosten-haushalt-berechnen/",
    name: "Stromkosten für den Haushalt",
    hint: "Jahresrechnung für den ganzen Haushalt.",
    parentName: "Energiekosten-Rechner",
    tags: [
      "Stromkosten Haushalt",
      "Stromrechnung",
      "Effektivpreis",
      "Grundpreis",
    ],
  },
  {
    href: "/tools/energiekosten/abschlag-berechnen/",
    name: "Abschlag berechnen",
    hint: "Wie hoch die monatliche Zahlung sein sollte.",
    parentName: "Energiekosten-Rechner",
    tags: [
      "Abschlag",
      "Vorauszahlung",
      "monatlich",
      "Abschlag senken",
      "Abschlag anpassen",
    ],
  },
  {
    href: "/tools/energiekosten/nachzahlung-stromrechnung/",
    name: "Nachzahlung Stromrechnung",
    hint: "Was bei der Jahresabrechnung fehlt.",
    parentName: "Energiekosten-Rechner",
    tags: [
      "Nachzahlung",
      "Stromrechnung",
      "Guthaben",
      "Jahresabrechnung",
      "Ratenzahlung",
    ],
  },
  {
    href: "/tools/energiekosten/stromverbrauch-4-personen-haushalt/",
    name: "Stromverbrauch 4-Personen-Haushalt",
    hint: "Normalwert und Kosten für vier Personen.",
    parentName: "Energiekosten-Rechner",
    tags: [
      "Stromverbrauch",
      "4 Personen",
      "Familie",
      "Durchschnitt",
      "Vergleichswert",
    ],
  },
  {
    href: "/tools/energiekosten/gasverbrauch-einfamilienhaus/",
    name: "Gasverbrauch Einfamilienhaus",
    hint: "Heizbedarf nach Wohnfläche und Dämmung.",
    parentName: "Energiekosten-Rechner",
    tags: [
      "Gasverbrauch",
      "Einfamilienhaus",
      "Heizen",
      "Dämmung",
      "kWh pro qm",
    ],
  },
  {
    href: "/tools/immobilienrechner/",
    name: "Immobilien-Rechner",
    hint: "Kaufnebenkosten, Mietrendite und Finanzierung.",
    tags: [
      "Immobilie",
      "Hauskauf",
      "Wohnung kaufen",
      "Kaufnebenkosten",
      "Grunderwerbsteuer",
      "Notar",
      "Makler",
      "Mietrendite",
      "Finanzierung",
      "Tilgung",
      "Kredit",
      "kaufen oder mieten",
    ],
  },
  {
    href: "/tools/aktienkennzahlen/",
    name: "Aktien-Kennzahlen-Rechner",
    hint: "Dreißig Kennzahlen aus einem Geschäftsbericht.",
    tags: [
      "Aktien",
      "Börse",
      "Kennzahlen",
      "Bewertung",
      "Dividende",
      "Bilanz",
      "Cashflow",
      "Fundamentalanalyse",
      "fairer Wert",
      "Geschäftsbericht",
    ],
  },
  {
    href: "/tools/aktienkennzahlen/kgv-berechnen/",
    name: "KGV berechnen",
    hint: "Kurs-Gewinn-Verhältnis einer Aktie berechnen.",
    parentName: "Aktien-Kennzahlen-Rechner",
    tags: [
      "KGV",
      "Kurs-Gewinn-Verhältnis",
      "P/E",
      "PE Ratio",
      "Gewinn je Aktie",
      "Bewertung",
    ],
  },
  {
    href: "/tools/aktienkennzahlen/kurs-buchwert-verhaeltnis/",
    name: "Kurs-Buchwert-Verhältnis berechnen",
    hint: "KBV einer Aktie berechnen.",
    parentName: "Aktien-Kennzahlen-Rechner",
    tags: ["KBV", "Kurs-Buchwert-Verhältnis", "P/B", "Buchwert", "Substanz"],
  },
  {
    href: "/tools/aktienkennzahlen/kurs-umsatz-verhaeltnis/",
    name: "Kurs-Umsatz-Verhältnis berechnen",
    hint: "KUV einer Aktie berechnen.",
    parentName: "Aktien-Kennzahlen-Rechner",
    tags: ["KUV", "Kurs-Umsatz-Verhältnis", "P/S", "Umsatzmultiplikator"],
  },
  {
    href: "/tools/aktienkennzahlen/peg-ratio/",
    name: "PEG-Ratio berechnen",
    hint: "KGV im Verhältnis zum Gewinnwachstum.",
    parentName: "Aktien-Kennzahlen-Rechner",
    tags: ["PEG", "PEG-Ratio", "Wachstum", "KGV Wachstum"],
  },
  {
    href: "/tools/aktienkennzahlen/dividendenrendite-berechnen/",
    name: "Dividendenrendite berechnen",
    hint: "Dividendenrendite und Ausschüttungsquote.",
    parentName: "Aktien-Kennzahlen-Rechner",
    tags: ["Dividendenrendite", "Dividende", "Ausschüttung", "Rendite"],
  },
  {
    href: "/tools/aktienkennzahlen/ausschuettungsquote-berechnen/",
    name: "Ausschüttungsquote berechnen",
    hint: "Ist die Dividende durch den Gewinn gedeckt?",
    parentName: "Aktien-Kennzahlen-Rechner",
    tags: ["Ausschüttungsquote", "Payout Ratio", "Dividende gedeckt"],
  },
  {
    href: "/tools/aktienkennzahlen/eigenkapitalrendite-berechnen/",
    name: "Eigenkapitalrendite berechnen",
    hint: "ROE einer Aktie berechnen.",
    parentName: "Aktien-Kennzahlen-Rechner",
    tags: ["Eigenkapitalrendite", "ROE", "Return on Equity", "Rentabilität"],
  },
  {
    href: "/tools/aktienkennzahlen/ev-ebitda-berechnen/",
    name: "EV/EBITDA berechnen",
    hint: "Unternehmenswert zum operativen Ergebnis.",
    parentName: "Aktien-Kennzahlen-Rechner",
    tags: [
      "EV/EBITDA",
      "Enterprise Value",
      "Unternehmenswert",
      "EBITDA",
      "Nettoschulden",
    ],
  },
  {
    href: "/tools/aktienkennzahlen/free-cashflow-rendite-berechnen/",
    name: "Free-Cashflow-Rendite berechnen",
    hint: "Cashflow-Rendite einer Aktie berechnen.",
    parentName: "Aktien-Kennzahlen-Rechner",
    tags: ["Free Cashflow", "FCF", "Cashflow-Rendite", "freier Cashflow"],
  },
  {
    href: "/tools/aktienkennzahlen/eigenkapitalquote-berechnen/",
    name: "Eigenkapitalquote berechnen",
    hint: "Bilanzstärke und Verschuldungsgrad prüfen.",
    parentName: "Aktien-Kennzahlen-Rechner",
    tags: ["Eigenkapitalquote", "Bilanzstärke", "Verschuldung", "Bilanz"],
  },
  {
    href: "/tools/sparplan/",
    name: "Sparplan-Rechner",
    hint: "Sparrate, Zinseszins, Steuern und Entnahme.",
    tags: [
      "Sparplan",
      "Zinseszins",
      "ETF",
      "sparen",
      "Rendite",
      "Vermögensaufbau",
      "Altersvorsorge",
      "Depot",
      "Abgeltungssteuer",
      "Vorabpauschale",
    ],
  },
  {
    href: "/tools/sparplan/zinseszinsrechner/",
    name: "Zinseszins berechnen",
    hint: "Kapital über die Jahre mit Zinseszins berechnen.",
    parentName: "Sparplan-Rechner",
    tags: ["Zinseszins", "Zinsen", "Kapital", "Verdopplung", "72er-Regel"],
  },
  {
    href: "/tools/sparplan/etf-sparplan-rechner/",
    name: "ETF-Sparplan berechnen",
    hint: "ETF-Sparplan mit TER, Steuern und Inflation.",
    parentName: "Sparplan-Rechner",
    tags: [
      "ETF",
      "ETF-Sparplan",
      "MSCI World",
      "TER",
      "Teilfreistellung",
      "Fonds",
    ],
  },
  {
    href: "/tools/sparplan/100-euro-sparplan/",
    name: "100 Euro im Monat sparen",
    hint: "Was aus 100 Euro monatlich wird.",
    parentName: "Sparplan-Rechner",
    tags: ["100 Euro", "kleine Sparrate", "monatlich sparen", "Sparplan"],
  },
  {
    href: "/tools/sparplan/500-euro-monatlich-sparen/",
    name: "500 Euro monatlich anlegen",
    hint: "Endkapital und spätere Entnahme aus 500 Euro.",
    parentName: "Sparplan-Rechner",
    tags: ["500 Euro", "monatlich anlegen", "Vermögensaufbau", "Entnahme"],
  },
  {
    href: "/tools/sparplan/sparplan-1-million/",
    name: "Eine Million sparen",
    hint: "Nötige Sparrate für eine Million Euro.",
    parentName: "Sparplan-Rechner",
    tags: ["Million", "Millionär", "Sparziel", "reich werden", "Sparrate"],
  },
  {
    href: "/tools/sparplan/sparrate-berechnen/",
    name: "Sparrate berechnen",
    hint: "Nötige Monatsrate für ein Sparziel.",
    parentName: "Sparplan-Rechner",
    tags: ["Sparrate", "Sparziel", "wie viel sparen", "Monatsrate"],
  },
  {
    href: "/tools/sparplan/vorabpauschale-berechnen/",
    name: "Vorabpauschale berechnen",
    hint: "ETF-Steuer im Januar mit Basiszins 2026.",
    parentName: "Sparplan-Rechner",
    tags: [
      "Vorabpauschale",
      "Basiszins",
      "ETF-Steuer",
      "thesaurierend",
      "InvStG",
    ],
  },
  {
    href: "/tools/sparplan/abgeltungssteuer-berechnen/",
    name: "Abgeltungssteuer berechnen",
    hint: "25 Prozent plus Soli und Kirchensteuer.",
    parentName: "Sparplan-Rechner",
    tags: [
      "Abgeltungssteuer",
      "Abgeltungsteuer",
      "Kapitalertragsteuer",
      "Sparerpauschbetrag",
      "Kirchensteuer",
    ],
  },
  {
    href: "/tools/sparplan/entnahmeplan-rechner/",
    name: "Entnahmeplan berechnen",
    hint: "Monatliche Entnahme aus einem Vermögen.",
    parentName: "Sparplan-Rechner",
    tags: ["Entnahmeplan", "Entnahme", "4-Prozent-Regel", "Ruhestand", "Rente"],
  },
  {
    href: "/tools/kreditrechner/",
    name: "Kredit-Rechner",
    hint: "Rate, Zinsen, Tilgungsplan und Effektivzins.",
    tags: [
      "Kredit",
      "Darlehen",
      "Ratenkredit",
      "Zinsen",
      "Tilgung",
      "Monatsrate",
      "Finanzierung",
      "Bank",
      "Schulden",
    ],
  },
  {
    href: "/tools/kreditrechner/effektiver-jahreszins-berechnen/",
    name: "Effektiven Jahreszins berechnen",
    hint: "Echte Kreditkosten nach Preisangabenverordnung.",
    parentName: "Kredit-Rechner",
    tags: [
      "Effektivzins",
      "effektiver Jahreszins",
      "Sollzins",
      "PAngV",
      "Bearbeitungsgebühr",
    ],
  },
  {
    href: "/tools/kreditrechner/annuitaetendarlehen-berechnen/",
    name: "Annuitätendarlehen berechnen",
    hint: "Gleichbleibende Rate mit Tilgungsplan.",
    parentName: "Kredit-Rechner",
    tags: ["Annuität", "Annuitätendarlehen", "Tilgungsplan", "Baufinanzierung"],
  },
  {
    href: "/tools/kreditrechner/sondertilgung-rechner/",
    name: "Sondertilgung berechnen",
    hint: "Wie viel Zinsen und Laufzeit sie spart.",
    parentName: "Kredit-Rechner",
    tags: [
      "Sondertilgung",
      "vorzeitig tilgen",
      "schuldenfrei",
      "Zinsersparnis",
    ],
  },
  {
    href: "/tools/kreditrechner/restschuld-berechnen/",
    name: "Restschuld berechnen",
    hint: "Was am Ende der Zinsbindung offen bleibt.",
    parentName: "Kredit-Rechner",
    tags: [
      "Restschuld",
      "Zinsbindung",
      "Anschlussfinanzierung",
      "Forward-Darlehen",
    ],
  },
  {
    href: "/tools/kreditrechner/umschuldung-rechner/",
    name: "Umschuldung berechnen",
    hint: "Was ein günstigerer Kredit spart.",
    parentName: "Kredit-Rechner",
    tags: ["Umschuldung", "umschulden", "Dispo", "ablösen", "Kredit tauschen"],
  },
  {
    href: "/tools/kreditrechner/autokredit-rechner/",
    name: "Autokredit berechnen",
    hint: "Rate und Kosten, auch gegen Leasing.",
    parentName: "Kredit-Rechner",
    tags: ["Autokredit", "Auto finanzieren", "Leasing", "Ballonfinanzierung"],
  },
  {
    href: "/tools/kreditrechner/10000-euro-kredit/",
    name: "10.000 Euro Kredit",
    hint: "Rate und Zinsen für 3, 5 und 7 Jahre.",
    parentName: "Kredit-Rechner",
    tags: ["10000 Euro", "kleiner Kredit", "Ratenkredit"],
  },
  {
    href: "/tools/kreditrechner/20000-euro-kredit/",
    name: "20.000 Euro Kredit",
    hint: "Rate, Laufzeit und Zinsen berechnen.",
    parentName: "Kredit-Rechner",
    tags: ["20000 Euro", "Ratenkredit", "Wunschrate"],
  },
  {
    href: "/tools/kreditrechner/50000-euro-kredit/",
    name: "50.000 Euro Kredit",
    hint: "Große Summe mit Sondertilgung rechnen.",
    parentName: "Kredit-Rechner",
    tags: ["50000 Euro", "großer Kredit", "Modernisierung", "KfW"],
  },
  {
    href: "/tools/bruttonetto/",
    name: "Brutto-Netto-Rechner",
    hint: "Was vom Gehalt übrig bleibt, Posten für Posten.",
    tags: [
      "Brutto",
      "Netto",
      "Gehalt",
      "Lohn",
      "Gehaltsrechner",
      "Lohnrechner",
      "Lohnsteuer",
      "Sozialabgaben",
      "Steuerklasse",
      "Verdienst",
    ],
  },
  {
    href: "/tools/bruttonetto/steuerklasse-1/",
    name: "Netto in Steuerklasse 1",
    hint: "Brutto-Netto für Ledige berechnen.",
    parentName: "Brutto-Netto-Rechner",
    tags: ["Steuerklasse 1", "Steuerklasse I", "ledig", "Single"],
  },
  {
    href: "/tools/bruttonetto/steuerklasse-3/",
    name: "Netto in Steuerklasse 3",
    hint: "Splittingtarif für Verheiratete berechnen.",
    parentName: "Brutto-Netto-Rechner",
    tags: [
      "Steuerklasse 3",
      "Steuerklasse III",
      "verheiratet",
      "Splitting",
      "Ehegattensplitting",
    ],
  },
  {
    href: "/tools/bruttonetto/steuerklasse-4/",
    name: "Netto in Steuerklasse 4",
    hint: "Für Verheiratete mit ähnlichem Einkommen.",
    parentName: "Brutto-Netto-Rechner",
    tags: [
      "Steuerklasse 4",
      "Steuerklasse IV",
      "Faktorverfahren",
      "Kinderfreibetrag",
    ],
  },
  {
    href: "/tools/bruttonetto/steuerklasse-5/",
    name: "Netto in Steuerklasse 5",
    hint: "Warum die Abzüge so hoch ausfallen.",
    parentName: "Brutto-Netto-Rechner",
    tags: ["Steuerklasse 5", "Steuerklasse V", "hohe Abzüge", "Klassenwechsel"],
  },
  {
    href: "/tools/bruttonetto/lohnsteuer-berechnen/",
    name: "Lohnsteuer berechnen",
    hint: "Steuertarif, Freibeträge und Rechenweg.",
    parentName: "Brutto-Netto-Rechner",
    tags: [
      "Lohnsteuer",
      "Einkommensteuer",
      "Grenzsteuersatz",
      "Grundfreibetrag",
      "Vorsorgepauschale",
    ],
  },
  {
    href: "/tools/bruttonetto/sozialabgaben-berechnen/",
    name: "Sozialabgaben berechnen",
    hint: "Alle vier Zweige mit Bemessungsgrenzen.",
    parentName: "Brutto-Netto-Rechner",
    tags: [
      "Sozialabgaben",
      "Sozialversicherung",
      "Rentenversicherung",
      "Krankenversicherung",
      "Pflegeversicherung",
      "Beitragsbemessungsgrenze",
    ],
  },
  {
    href: "/tools/bruttonetto/kirchensteuer-berechnen/",
    name: "Kirchensteuer berechnen",
    hint: "8 oder 9 Prozent der Lohnsteuer.",
    parentName: "Brutto-Netto-Rechner",
    tags: [
      "Kirchensteuer",
      "Kirchenaustritt",
      "Kirche",
      "8 Prozent",
      "9 Prozent",
    ],
  },
  {
    href: "/tools/bruttonetto/arbeitgeberkosten-berechnen/",
    name: "Arbeitgeberkosten berechnen",
    hint: "Was eine Stelle wirklich kostet.",
    parentName: "Brutto-Netto-Rechner",
    tags: [
      "Arbeitgeberkosten",
      "Lohnnebenkosten",
      "Arbeitgeberbrutto",
      "Personalkosten",
    ],
  },
  {
    href: "/tools/bruttonetto/gehaltserhoehung-netto/",
    name: "Gehaltserhöhung netto",
    hint: "Was von 100 Euro mehr übrig bleibt.",
    parentName: "Brutto-Netto-Rechner",
    tags: [
      "Gehaltserhöhung",
      "Grenzbelastung",
      "mehr Gehalt",
      "Gehaltsverhandlung",
      "Sachbezug",
    ],
  },
  {
    href: "/tools/rentenluecke/",
    name: "Rentenlücken-Rechner",
    hint: "Kapitalbedarf und Sparrate für den Ruhestand.",
    tags: [
      "Rentenlücke",
      "Altersvorsorge",
      "gesetzliche Rente",
      "Kapitalbedarf",
      "Versorgungsniveau",
      "Ruhestand",
      "Rentenniveau",
      "Sparrate Rente",
      "private Vorsorge",
    ],
  },
  {
    href: "/tools/elterngeld/",
    name: "Elterngeld-Rechner",
    hint: "Ersatzrate, Boni und ElterngeldPlus im Vergleich.",
    tags: [
      "Elterngeld",
      "ElterngeldPlus",
      "Basiselterngeld",
      "Geschwisterbonus",
      "Mehrlingszuschlag",
      "Ersatzrate",
      "Elternzeit Geld",
      "Partnermonate",
    ],
  },
  {
    href: "/tools/rentenabschlag/",
    name: "Rentenabschlags-Rechner",
    hint: "Abschlag oder Zuschlag je nach Renteneintritt.",
    tags: [
      "Rentenabschlag",
      "Regelaltersgrenze",
      "früher in Rente",
      "Rente mit 63",
      "Rentenzuschlag",
      "Renteneintrittsalter",
      "Zugangsfaktor",
    ],
  },
  {
    href: "/tools/abfindung/",
    name: "Abfindungsrechner",
    hint: "Fünftelregelung: Steuer auf die Abfindung.",
    tags: [
      "Abfindung",
      "Fünftelregelung",
      "Abfindung versteuern",
      "Abfindung netto",
      "Kündigung Steuer",
      "Aufhebungsvertrag",
    ],
  },
  {
    href: "/tools/erbschaftsteuer/",
    name: "Erbschaft- und Schenkungsteuer-Rechner",
    hint: "Freibetrag, Steuerklasse und Härteausgleich.",
    tags: [
      "Erbschaftsteuer",
      "Schenkungsteuer",
      "Erbschaft",
      "Schenkung",
      "Freibetrag",
      "Steuerklasse",
      "Härteausgleich",
      "ErbStG",
      "Nachlass",
    ],
  },
  {
    href: "/tools/versicherungsvergleich/",
    name: "Versicherungs-Vergleichsrechner",
    hint: "Marktdurchschnitt für Kfz, Haftpflicht und BU.",
    tags: [
      "Versicherungsvergleich",
      "Kfz-Versicherung",
      "Privathaftpflicht",
      "Berufsunfähigkeitsversicherung",
      "BU",
      "Durchschnittsbeitrag",
      "Schadenfreiheitsklasse",
      "zu teuer versichert",
      "Prämie vergleichen",
    ],
  },
  {
    href: "/tools/autokosten/",
    name: "Auto-Unterhaltskosten-Rechner",
    hint: "Wertverlust, Sprit, Steuer und Versicherung.",
    tags: [
      "Autokosten",
      "Unterhaltskosten",
      "Wertverlust",
      "Kraftstoffkosten",
      "Kfz-Steuer",
      "Kfz-Versicherung",
      "Kosten pro Kilometer",
      "Auto Unterhalt",
      "Elektroauto Kosten",
    ],
  },
  {
    href: "/tools/bmi/",
    name: "BMI-Rechner",
    hint: "Body-Mass-Index mit WHO-Kategorie.",
    tags: [
      "BMI",
      "Body Mass Index",
      "BMI berechnen",
      "Normalgewicht",
      "Idealgewicht",
      "Übergewicht",
      "BMI Tabelle",
      "BMI Rechner",
    ],
  },
  {
    href: "/tools/kalorienbedarf/",
    name: "Kalorienbedarf-Rechner",
    hint: "Grundumsatz und Gesamtumsatz pro Tag.",
    tags: [
      "Kalorienbedarf",
      "Grundumsatz",
      "Gesamtumsatz",
      "Kalorien pro Tag",
      "Mifflin-St Jeor",
      "PAL",
      "Kalorienrechner",
      "Aktivitätsfaktor",
    ],
  },
  {
    href: "/wege/hauskauf/",
    name: "Check: Hauskauf",
    hint: "Immobilie und Einkommen zusammen: leistbar oder nicht?",
    tags: [
      "Hauskauf",
      "Haus kaufen",
      "kann ich mir ein Haus leisten",
      "wie viel Haus kann ich mir leisten",
      "Belastungsquote",
      "Baufinanzierung tragbar",
      "Immobilie leisten",
    ],
  },
  {
    href: "/wege/gehalt/",
    name: "Check: Gehaltserhöhung",
    hint: "Brutto-Plus, Netto-Plus und Grenzbelastung in einem Zug.",
    tags: [
      "Gehaltserhöhung",
      "Gehaltserhöhung netto",
      "Grenzbelastung",
      "was bringt gehaltserhöhung",
      "gehaltserhöhung berechnen",
      "gehaltserhöhung sparen",
    ],
  },
  {
    href: "/wege/gehalt/3-prozent/",
    name: "3 Prozent mehr Gehalt",
    hint: "Was von 3 Prozent Erhöhung netto ankommt.",
    parentName: "Check: Gehaltserhöhung",
    tags: ["3 Prozent", "kleine Erhöhung"],
  },
  {
    href: "/wege/gehalt/5-prozent/",
    name: "5 Prozent mehr Gehalt",
    hint: "Was von 5 Prozent Erhöhung netto ankommt.",
    parentName: "Check: Gehaltserhöhung",
    tags: ["5 Prozent", "übliche Erhöhung"],
  },
  {
    href: "/wege/gehalt/10-prozent/",
    name: "10 Prozent mehr Gehalt",
    hint: "Was von 10 Prozent Erhöhung netto ankommt.",
    parentName: "Check: Gehaltserhöhung",
    tags: ["10 Prozent", "Stellenwechsel", "Beförderung"],
  },
  {
    href: "/wege/gehalt/15-prozent/",
    name: "15 Prozent mehr Gehalt",
    hint: "Was von 15 Prozent Erhöhung netto ankommt.",
    parentName: "Check: Gehaltserhöhung",
    tags: ["15 Prozent", "großer Sprung", "Jobwechsel"],
  },
  {
    href: "/wege/ruhestand/",
    name: "Check: Ruhestand",
    hint: "Rente nach Abschlag, Kapitalbedarf und Sparrate zusammen.",
    tags: [
      "Früher in Rente",
      "Rente mit 63",
      "Renteneintritt vorziehen",
      "kann ich früher in rente gehen",
      "wann kann ich in rente gehen",
      "Rentenlücke",
      "Rentenabschlag",
    ],
  },
  {
    href: "/wege/autokauf/",
    name: "Check: Auto",
    hint: "Kreditrate, Unterhalt und Versicherung gegen das Netto.",
    tags: [
      "Autokauf",
      "Auto finanzieren",
      "was kostet ein auto wirklich",
      "kann ich mir das auto leisten",
      "Autokosten Rate",
      "Auto Gesamtkosten",
    ],
  },
  {
    href: "/wege/nachwuchs/",
    name: "Check: Nachwuchs",
    hint: "Termin, Einkommen, Elterngeld und Elternzeit zusammen.",
    tags: [
      "Elterngeld",
      "Elternzeit",
      "Kindergeld",
      "was bringt elterngeld",
      "elternzeit planen",
      "geburtstermin",
      "Nachwuchs",
    ],
  },
  {
    href: "/tools/prozentrechner/",
    name: "Prozentrechner",
    hint: "Anteil, Grundwert, Prozentsatz oder Veränderung berechnen.",
    tags: [
      "Prozentrechner",
      "Prozent berechnen",
      "Prozentsatz",
      "Grundwert",
      "Prozentwert",
      "Rabatt berechnen",
      "wie viel Prozent",
      "prozentuale Veränderung",
    ],
  },
  {
    href: "/tools/geburtstermin/",
    name: "Geburtstermin-Rechner",
    hint: "Errechneter Termin und Schwangerschaftswoche.",
    tags: [
      "Geburtstermin",
      "SSW",
      "Schwangerschaftswoche",
      "errechneter Termin",
      "Naegele-Regel",
      "Schwangerschaftskalender",
      "Entbindungstermin",
      "Trimester",
    ],
  },
];
